spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blogapi?ssl=false
    # &serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: postgres
    password: mdohKkXhh2
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

app:
  jwtSecret: secret
  jwtExpirationInMs: 3600000

cors:
  allowedOrings: '*'
